/* #project on ECG-EG  */

proc import datafile="/home/u64168920/ADaM_poj/Project ADAM-BDS EG Raw data.xlsx"
out=EG
DBMS=XLSX REPLACE;
GETNAMES=YES;
RUN;

DATA EG;
SET WORK.EG;
RUN;

PROC IMPORT DATAFILE="/home/u64168920/ADaM_poj/Project ADAM-BDS suppADAE Raw data.xlsx"
OUT=SUPPEG
DBMS=XLSX REPLACE;
GETNAMES=YES;
RUN;

DATA SUPPEG;
SET WORK.SUPPEG;
RUN;

/* MERGE BOTH THE DATASET */
PROC SORT DATA=EG;BY USUBJID EGSEQ;RUN;

PROC SORT DATA=SUPPEG;BY USUBJID EGSEQ;RUN;

DATA ADEG;
MERGE EG SUPPEG;
BY USUBJID EGSEQ;
RUN;

DATA ADEG1;
SET ADEG;
AVAL=INPUT(EGSTRESN,BEST.);
ABLFL=EGBLFL;
PARAM=EGTEST;

if LENGTH(EGDTC) > 10 THEN DO;
ADT=INPUT(SUBSTR(EGDTC,1,10),YYMMDD10.);
ATM=INPUT(SUBSTR(EGDTC,12),TIME8.);
END;
ELSE DO;
ADT=INPUT(SUBSTR(EGDTC,1,10),YYMMDD10.);
END;
FORMAT ADT DATE9. ATM TIME8.;
AVISIT=VISITNUM/10;
AVISIT=VISIT;
RUN;

DATA ADE;
SET ADEG1;
WHERE ABLFL="Y";
KEEP EGBLFL EGSTRESN VISIT;
RUN;

DATA ADEG2;
SET ADEG1;
RETAIN BASE;
IF ABLFL="Y" THEN DO;
BASE=AVAL;
END;
KEEP BASE AVAL ABLFL;
RUN;

DATA ADEG3;
SET ADEG2;
IF AVAL NE . AND BASE NE . THEN CHG=AVAL-BASE;
IF CHG NE . AND NOT IN(.,0) THEN PCHG=(CHG*100)/BASE;
KEEP
STUDYID
USUBJID
EGEVAL
EGCAT
AVAL
AVALC
ABLFL
PARAM
PARAMCD
ADT
ATM
AVISITN
AVISIT
Base
CHG
PCHG;
RUN;
