*SAS MACROS - CONDITIONAL AND ITERATIVE STATMENT*/;
USING CONDITIONAL STATMENT AND LOOPS USING MACRO STATMENT SUCH AS %IF %THEN %ELSE %DO %END
THESE MACRO STATMENT SHOULD ALWAYS BE CALLED INSIDE THE MACRO.

CONDIDITONAL PROCESSING:
CONDITIONAL PROCESSING IS USED WHEN WE WANT TO EXECUTE A PIECE OF CODE BASSED ON THE OUTPUT ON 
THE OUTPUT OF SINGLE OR MULTIPLE CONDITIONS*/;

/* SYNTAX */
%IF <CONDITIONAL MACRO EXPRESSION > %THEN <TRUE TEXT>;

OF %IF <CONDITIONAL MACRO EXPRESSION>%THEN %DO;
TEXT1;
TEXT2;
.
.
.
%END;
%ELSE %DO;
TEXT1;
TEXT2;
.
.
TEXTN;
%END;
