/* IMPORT ADSL SOURCE DATA */

PROC IMPORT DATAFILE="/HOME/U64252598/PROJECT AE TABLE RAW FILE ADVERSE_ADSL.XLSX"
OUT=AE
DBMS=XLSX
REPLACE;
GETNAMES=YES;
RUN;


/* CHECK DATA */

PROC CONTENTS DATA=AE;
RUN;

PROC MEANS DATA=AE N NMISS MEAN MEDIAN SUM MAX MIN STD;
VAR _NUMERIC_;
RUN;

PROC FREQ DATA=AE;
TABLES _CHARACTER_ / MISSING;
RUN;


/* SAFETY POPULATION */

DATA AE_01;
SET AE;
IF SAFFL="Y";
RUN;


/* CREATE TREATMENT ORDER FOR BIG N */

DATA ADSL2;
SET AE_01;

IF INDEX(UPCASE(TRT01A),"100 MG TG3304")>0 THEN DO;
   TRT="A";
   ORD=1;
END;

ELSE IF INDEX(UPCASE(TRT01A),"PLACEBO")>0 THEN DO;
   TRT="B";
   ORD=2;
END;

KEEP USUBJID TRT ORD;
RUN;


/* CALCULATE BIG N */

PROC SQL NOPRINT;
SELECT COUNT(DISTINCT USUBJID)
INTO :N1-:N2
FROM ADSL2
GROUP BY ORD
ORDER BY ORD;
QUIT;

%PUT &=N1 &=N2;


/* IMPORT ADAE */

PROC IMPORT DATAFILE="/HOME/U64252598/PROJECT AE TABLE RAW FILE ADVERSE_ADAE.XLSX"
OUT=ADAE
DBMS=XLSX
REPLACE;
GETNAMES=YES;
RUN;


/* TREATMENT EMERGENT ADVERSE EVENTS */

DATA ADAE1;
SET ADAE;

IF SAFFL="Y" AND TEAEFL="Y";

IF INDEX(UPCASE(TRTA),"100 MG TG3304")>0 THEN DO;
   TRT="A";
   ORD=1;
END;

ELSE IF INDEX(UPCASE(TRTA),"PLACEBO")>0 THEN DO;
   TRT="B";
   ORD=2;
END;
RUN;


/* OVERALL SUBJECT COUNT */

PROC SQL;

CREATE TABLE ANY AS
SELECT TRT,
       COUNT(DISTINCT USUBJID) AS N,
       "NUMBER OF SUBJECTS WITH TRTS" AS AEBODSYS LENGTH=200
FROM ADAE1
GROUP BY TRT;


/* SOC LEVEL */

CREATE TABLE SOS AS
SELECT TRT,
       AEBODSYS,
       COUNT(DISTINCT USUBJID) AS N
FROM ADAE1
GROUP BY TRT,AEBODSYS;


/* PT LEVEL */

CREATE TABLE PT AS
SELECT TRT,
       AEBODSYS,
       AEDECOD,
       COUNT(DISTINCT USUBJID) AS N
FROM ADAE1
GROUP BY TRT,AEBODSYS,AEDECOD;

QUIT;


/* STACK ALL LEVELS */

DATA ALL;
SET ANY SOS PT;
RUN;


PROC SORT DATA=ALL;BY AEBODSYS AEDECOD TRT;RUN;
PROC TRANSPOSE DATA=ALL OUT=ALL_1;
ID TRT;
BY AEBODSYS AEDECOD;
RUN;

DATA FINAL;
SET ALL_1;

LENGTH DRUGA DRUGB $100 AEBODSYS1 $200;

IF A=. THEN DRUGA='0';
ELSE IF A=&N1 THEN DRUGA=PUT(A,3.)||'(100%)';
ELSE DRUGA=PUT(A,3.)||'('||PUT(A/&N1*100,4.1)||'%)';

IF B=. THEN DRUGB='0';
ELSE IF B=&N2 THEN DRUGB=PUT(B,3.)||'(100%)';
ELSE DRUGB=PUT(B,3.)||'('||PUT(B/&N2*100,4.1)||'%)';

IF MISSING(AEDECOD) AND NOT MISSING(AEBODSYS)
THEN AEBODSYS1=AEBODSYS;
ELSE AEBODSYS1='   '||AEDECOD;

RUN;

ODS ESCAPECHAR='^';

PROC REPORT DATA=FINAL NOWD HEADLINE HEADSKIP SPLIT='|';

COLUMN AEBODSYS AEDECOD
       AEBODSYS1
       ("TREATMENT"
        DRUGA
        DRUGB);

DEFINE AEBODSYS / ORDER NOPRINT;
DEFINE AEDECOD  / ORDER NOPRINT;

DEFINE AEBODSYS1 / DISPLAY
"MEDDRA@ SYSTEM ORGAN CLASS|MEDDRA@ PREFERRED TERM"
STYLE(COLUMN)=[JUST=L CELLWIDTH=45%];

DEFINE DRUGA / DISPLAY
"100 MG TG3304|(N=&N1)"
STYLE(COLUMN)=[JUST=CENTER];

DEFINE DRUGB / DISPLAY
"PLACEBO|(N=&N2)"
STYLE(COLUMN)=[JUST=CENTER];

COMPUTE BEFORE _PAGE_;
LINE " ";
LINE @40 "TABLE 14.2.1";
LINE @5 "TREATMENT EMERGENT ADVERSE EVENTS BY TREATMENT, SYSTEM ORGAN CLASS AND PREFERRED TERM";
LINE @40 "(SAFETY POPULATION)";
LINE " ";
ENDCOMP;

RUN;


