/* PROC FREQ */
/* NOCUM NOFREQ NOPCT NOROW NOCOL */

PROC FREQ DATA=SASHELP.CLASS ;
TABLE AGE;
QUIT;

PROC FREQ DATA=SASHELP.CLASS;
TABLE AGE HEIGHT WEIGHT/NOCUM NOFREQ ;
QUIT;

PROC FREQ DATA=SASHELP.CLASS;
TABLES AGE*HEIGHT;
QUIT;

PROC FREQ DATA=SASHELP.CLASS;
TABLES AGE*HEIGHT/NOFREQ;
QUIT;

PROC FREQ DATA=SASHELP.CLASS;
TABLES AGE*HEIGHT/NOFREQ NOCOL NOROW NOPCT;
QUIT;
