**************************12/03/2026***********************************
;
PROC MEANS DATA=DSN;
VAR VARLIST;
CLASS CLASSIFICATION_VARLIST;
BY VARLIST;
QUIT;

PROC MEANS DATA=SASHELP.CLASS;
VAR AGE HEIGHT WEIGHT;
QUIT;

PROC MEANS DATA=SASHELP.CLASS;
VAR AGE HEIGHT WEIGHT;
CLASS NAME;
QUIT;

PROC SORT DATA=SASHELP.CLASS OUT=A;
BY AGE;
QUIT;

PROC MEANS DATA=A;
VAR HEIGHT WEIGHT;
CLASS AGE;
BY AGE;
QUIT;

/* PROC SUMMARY */

PROC SUMMARY DATA=DNS;
VAR VARLIST;
CLASS VARLIST;
BY VARLIST;
OUTPUT OUT=DSN;
QUIT;

PROC SUMMARY DATA=A;
VAR AGE HEIGHT WEIGHT;
CLASS NAME;
BY AGE;
OUTPUT OUT=B;
QUIT;

/* TO PRINT THE REPORT (PRINT SHOULD BE MENCTIONED) */

PROC SUMMARY DATA=A PRINT;
VAR AGE HEIGHT WEIGHT;
CLASS NAME;
BY AGE;
OUTPUT OUT=B;
QUIT;

/*DIFFRENT BETWEEN PROC MEANS AND PROC SUMMARY?

PROC MENAS , BY DEFAULT PRINTES A REPORT IN THE RESULTS VIEWS WINDOW
BUT PROC SUMMMARY , DOES NOT PRINT REPORT UNLESS PRINT OPTION IS GIVEN*/

    PROC APPEND-->ADDING OBSERVATON FROM ONE DATASET TO NASE DATASET

1.VARIABLES MUST BE SAME
2.ONLY DATASETS ARE POSSIBLE WITH SAME VARIABLES
3.IF THE DATASETS ARE HAVING UNCOMMON VARIABLE, FORCE OPTION MUST BE USED
;

PROC APPEND BASE=DSN SATA=DSN;
QUIT;

DATA A;
INPUT ID NAME$;
CARDS;
101 AB
102 DE
103 CD
;RUN;

DATA B;
INPUT ID NAME$;
CARDS;
103 OO
104 11
;
RUN;

PROC APPEND BASE=A DATA=B FORCE;
QUIT;
