********************************************************************************************
*****************************06/03/2026*****************************************************
********************************************************************************************

 
/* INTERlEAVING -->COMBINING SORTED DATASET VERTICALLY; 

DATA DSN;
SET DS1 DS2;
BY VAR;
RUN;

PROC SORT DATA=SASHELP.CLASS OUT=A;
BY AGE;
QUIT;
PROC SORT DATA=SASHELP.CLASSFIT OUT=B;
BY AGE;
QUIT;


DATA NITHI;
SET A B;
BY AGE;
RUN;

FIRST .VAR LAST.VAR

FIRST.VAR-->FIRST OCCURANCE
LAST.VAR-->LAST OCCURANCE

/* FIRST OCCURANCE  */;
 TITLE "FIRST OCCURANCE";
DATA N;
SET A;
BY AGE;
IF FIRST.AGE;
RUN;

PROC PRINT DATA=N;
QUIT;

/* LAST OCCURANCE  */;
 TITLE "LAST OCCURANCE";
DATA M;
SET A;
BY AGE;
IF LAST.AGE;
RUN;

PROC PRINT DATA=M;
QUIT;

/* UNIQUE OCCURANCE */

DATA J;
SET A;
BY AGE;
IF FIRST.AGE AND LAST.AGE;
RUN;

PROC PRINT DATA=J;
QUIT;

/* EXAMPLE 2 */
PROC SORT DATA=SASHELP.CLASS OUT=A;
BY WEIGHT;
QUIT;

DATA K;
SET A;
BY WEIGHT;
IF FIRST.WEIGHT AND LAST.WEIGHT;
RUN;

PROC PRINT DATA=K;
QUIT;

/* TO CANCULATE NUMBER OF OCCURANCE */
PROC SORT DATA=SASHELP.CLASS OUT=X;
BY AGE;
QUIT;

DATA AB;
SET X;
BY AGE;
IF FIRST.AGE THEN COUNT=1;
ELSE COUNT+1;
RUN;

/* EXAMPLE2 */
PROC SORT DATA=SASHELP.CLASS OUT=X;
BY SEX;
QUIT;

DATA AB;
SET X;
BY SEX;
IF FIRST.SEX THEN COUNT=1;
ELSE COUNT+1;
RUN;

*IN HOW MANY WAYS DUPLICATE ARE REMOVED IN SAS?

USING PROC SORT ,NODUPKEY,NODUP
USING INTERLEAVING,FIRST.VAR AND LAST.VAR;

PROC SORT DATA=SASHELP.CLASS NODUPKEY OUT=X DUPOUT=Y;
BY AGE;
QUIT;
