/* DATE FUNCTIONS */

/*DATA VALUE  INFORMAT. FORMATS 

01/12/2003  DMMYY10.  DDMMYY10.

23-12-2003  DDMMYY10. DDMMYY10.

23:12:2003  DDMMYY10. DDMMYY10.

23.12.2003  DDMMYY10. DDMMYY10.

23 12 2003  DDMMYY10. DDMMYY10.

12DEC2003   DATE9.     DATE9.

12-DEC-2003  DATE11.   DATE11. */

/*
Common Date Functions Used in SDTM (SAS)

year = YEAR(date_variable);
month = MONTH(date_variable);
day = DAY(date_variable);
new_date = MDY(month, day, year);
iso_date = PUT(date_variable, IS8601DA.);

Converts SAS date into ISO 8601 format, 
which is required for SDTM variables like –DTC.

sas_date = INPUT(char_date, yymmdd10.);*/

INFORMAT -->TO READ NON STANDARD DATE VALUES;
FORMAT-->TO WRITE THE DATA IN REQUIRED FORMAT;

/* DAY,MONTH,YEAR,QTR,WEEK,INTCK,INTNX */

DATA NITH;
D="31DEC2005"D;
FORMAT D DATE9.;
D1=DAY(D);
M1=MONTH(D);
Y1=YEAR(D);
Q1=QTR(D);
W1=WEEK(D);
RUN;

PROC PRINT DATA=NITH;
RUN;

INTCK-->CHECKS THE NUMBER OF INTERVALS BETWEEN TWO DATES

/* GENERAL SYNTAX  

VARIABLE=INTCK("INTERVAL",FROM,TO);

*/;

DATA A;
D="06NOV2005"D;
E="04FEB2006"D;
FORMAT D E DATE9.;
DY=INTCK("DAYS",D,E);
MY=INTCK("MONTHS",D,E);
YR=INTCK("YEARS",D,E);
RUN;

INTNX-->INTERVAL NEXT FUNCTION->TO CALCULATETHE FUTURE DATE
FROM THE GIVEN NUMBER OF INTERCALS

/*GENERAL SYNTAX

VARIABLES=INTNX("INTERVAL",FROM,NO OF INTERVALS);

*/;

DATA G;
P="12JAN2020"D;
DY=INTNX("DAYS",P,10);
MN=INTNX("MONTHS",P,10);
YR=INTNX("YEARS",P,3);
FORMAT P DY MN YR DATE9.;
RUN;

PROC PRINT DATA=G;
RUN;
