/*ODS-->OUTPUT DELIVERY SYSTEM

-->SAS REPORT TO DIFFRENT FORMATES*/

PROC COMPARE DATA=SASHELP.CLASS COMPARE=SASHELP.CLASSFIT;
QUIT;

PROC PRINT DATA=SASHELP.CLASS;
QUIT;

PROC MEANS DATA=SASHELP.CLASS;
QUIT;

/* PDF OUTPUT OUTPUT FILE */

ODS PDF FILE="/home/u64168920/EPG1V2/data/CLASSDATA.PDF";

PROC COMPARE DATA=SASHELP.CLASS COMPARE=SASHELP.CLASSFIT;
QUIT;

PROC PRINT DATA=SASHELP.CLASS;
QUIT;

PROC MEANS DATA=SASHELP.CLASS;
QUIT;

ODS PDF CLOSE;

/* FOR EXCEL OUTPUT FILE*/

ODS EXCEL FILE="/home/u64168920/EPG1V2/data/CLASSDATA1.XLS";

PROC COMPARE DATA=SASHELP.CLASS COMPARE=SASHELP.CLASSFIT;
QUIT;

PROC PRINT DATA=SASHELP.CLASS;
QUIT;

PROC MEANS DATA=SASHELP.CLASS;
QUIT;

ODS EXCEL CLOSE;


/* FOR POWERPOINT OUTPUT FILE */

ODS POWERPOINT FILE="/home/u64168920/EPG1V2/data/CLASSDATA2.PPTX";

PROC COMPARE DATA=SASHELP.CLASS COMPARE=SASHELP.CLASSFIT;
QUIT;

PROC PRINT DATA=SASHELP.CLASS;
QUIT;

PROC MEANS DATA=SASHELP.CLASS;
QUIT;

ODS POWERPOINT CLOSE;

/* FOR WORD FORMATE OUTPUT FILE */
ODS RTF FILE ="/home/u64168920/EPG1V2/data/CLASSDATA3.RTF";

PROC COMPARE DATA=SASHELP.CLASS COMPARE=SASHELP.CLASSFIT;
QUIT;

PROC PRINT DATA=SASHELP.CLASS;
QUIT;

PROC MEANS DATA=SASHELP.CLASS;
QUIT;

ODS RTF CLOSE;

/* PROC IMPORT PREOCEDURE FOR TEXT FILE */

GENERAL SUNTAX;

PROC IMPORT DATAFILE=DSN
OUT=OUTPUT-FILE-NAME
DBMS=DLM REPLACE;
DELIMITER="";
DATAROW=2;
GETNAMES=YES;
QUIT;

PROC IMPORT DATAFILE="/home/u64168920/EPG1V2/data/excel file.xls"
OUT=NITHI
DBMS=XLS REPLACE;
GETNAMES=YES;
QUIT;

PROC IMPORT DATAFILE="/home/u64168920/EPG1V2/data/text file.txt"
OUT=NITHI1
DBMS=DLM REPLACE;
DELIMITER=",";
DATAROW=2;
GETNAMES=YES;
QUIT;

