PROC FREQ -->TO CALCULATE NUMBER OF OCCURANCE AND THEIR FREQUENCY 
PERSENTAGE AND REPRESENTING INFRORM OF TABLE

/* GENERAL SYNTAX */

/* PROC FREQ DATA=DSN;
TABLES VARLIST/OPTIONS'
QUIT;

LIST OF OPTIONS

NOROWS==>REMOVE ROW PERCENTAGE
NOCOL==> TO REMOVE COLUMN PERSENTAGE
NOFREQ==>TO REMOVE FREQ PCT
NOPCT==>TO REMOVE THE PCT */

PROC FREQ DATA=SASHELP.CLASS;
TABLES AGE;
RUN;

/* FREQ,PUT,CUMULATIVE FREQ,CUMULATIVE PCT */

PROC FREQ DATA=SASHELP.CLASS;
TABLES AGE*HEIGHT;
QUIT;

PROC FREQ DATA=SASHELP.CLASS;
TABLES AGE*HEIGHT/NOFREQ;
QUIT;

PROC FREQ DATA=SASHELP.CLASS;
TABLES AGE*HEIGHT/NOFREQ NOCOL NOROW NOPCT;
QUIT;

PROC FREQ DATA=SASHELP.DEMOGRAPHICS;
TABLES GNI/MISSING;
QUIT;

/* HEAR PROC GCHART USES PROC FREQ */
PROC GCHART DAT=SASHELP.CLASS;
HBAR3D AGE;
RUN;
QUIT;
